version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build phase complete. No compilation needed for HTML.
  post_build:
    commands:
      - chmod +x restart_httpd.sh
      - echo Build completed successfully.

artifacts:
  files:
    - index.html
    - appspec.yml
    - restart_httpd.sh
